In [64]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch

Understanding training pipeline with real world dataset

Getting data

In [65]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [66]:
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [67]:
df.describe()

                 id  radius_mean  ...  fractal_dimension_worst  Unnamed: 32
count  5.690000e+02   569.000000  ...               569.000000          0.0
mean   3.037183e+07    14.127292  ...                 0.083946          NaN
std    1.250206e+08     3.524049  ...                 0.018061          NaN
min    8.670000e+03     6.981000  ...                 0.055040          NaN
25%    8.692180e+05    11.700000  ...                 0.071460          NaN
50%    9.060240e+05    13.370000  ...                 0.080040          NaN
75%    8.813129e+06    15.780000  ...                 0.092080          NaN
max    9.113205e+08    28.110000  ...                 0.207500          NaN

[8 rows x 32 columns]

In [68]:
df.shape

(569, 33)

In [69]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [70]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

Splitting data

In [71]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[: , 0], test_size= 0.2)

Scaling data

In [72]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [73]:
X_train

array([[-0.29257905,  0.00751113, -0.36911721, ..., -1.54860766,
        -0.73872645, -1.18067204],
       [-0.34008073, -0.24538395, -0.29447693, ..., -0.05437634,
        -0.50338826,  0.32018611],
       [-0.14169135,  0.59450614, -0.18454478, ..., -0.7782039 ,
        -0.7272064 , -0.75704273],
       ...,
       [ 3.25048764, -0.42171447,  3.34626482, ...,  2.46407629,
         1.32007127,  0.27522953],
       [ 1.5963114 ,  0.66643043,  1.55327557, ...,  1.90576872,
        -0.19728404, -0.41641017],
       [-0.84862816, -1.00174907, -0.8202041 , ..., -0.08623628,
         0.67988557,  0.42796663]])

In [74]:
y_train

58     B
518    B
267    B
469    B
340    B
      ..
6      M
543    B
352    M
18     M
342    B
Name: diagnosis, Length: 455, dtype: object

Label Encoder

In [75]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

NP arrays to Tensors

In [76]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [77]:
X_train_tensor

tensor([[-0.2926,  0.0075, -0.3691,  ..., -1.5486, -0.7387, -1.1807],
        [-0.3401, -0.2454, -0.2945,  ..., -0.0544, -0.5034,  0.3202],
        [-0.1417,  0.5945, -0.1845,  ..., -0.7782, -0.7272, -0.7570],
        ...,
        [ 3.2505, -0.4217,  3.3463,  ...,  2.4641,  1.3201,  0.2752],
        [ 1.5963,  0.6664,  1.5533,  ...,  1.9058, -0.1973, -0.4164],
        [-0.8486, -1.0017, -0.8202,  ..., -0.0862,  0.6799,  0.4280]],
       dtype=torch.float64)

In [78]:
X_train_tensor.shape

torch.Size([455, 30])

In [79]:
X_test_tensor.shape

torch.Size([114, 30])

Defining the model - NN

In [80]:
class MySimpleNN():
    
    def __init__(self, X): # X is input data
        
        # Initialize random weights
        self.weights = torch.rand(X.shape[1], 1, dtype= torch.float64, requires_grad= True)
        
        #Initial Bias
        self.bias = torch.zeros(1, dtype= torch.float64, requires_grad= True)
        
        
    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    
    def loss(self, y_pred, y):
        epsilon = 1e-8
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        loss = -(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred)).mean()
        return loss

Important params

In [81]:
lr = 0.1
epochs = 50

Training Pipeline

In [82]:
# 1. Create model
model = MySimpleNN(X_train_tensor)

## These steps in loop - epochs ##

for epoch in range(epochs):    

    # 2. Forward pass
    y_pred = model.forward(X_train_tensor)
    # print(y_pred)
    
    # 3. Loss
    loss = model.loss(y_pred, y_train_tensor)
    
    
    # 4. Back pass
    loss.backward()
    
    # 5. Params update
    with torch.no_grad():
        model.weights -= lr*model.weights.grad
        model.bias -= lr*model.bias.grad
    
    # 6. Zero 
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    
    print(f"Epoch = {epoch + 1}, loss = {loss}")

Epoch = 1, loss = 2.951928720455751
Epoch = 2, loss = 2.795759144130985
Epoch = 3, loss = 2.630386597588412
Epoch = 4, loss = 2.461292175060563
Epoch = 5, loss = 2.293408683910202
Epoch = 6, loss = 2.1253256938584415
Epoch = 7, loss = 1.959377259686692
Epoch = 8, loss = 1.791183846478925
Epoch = 9, loss = 1.6312051228342264
Epoch = 10, loss = 1.477346483837399
Epoch = 11, loss = 1.3364317345877197
Epoch = 12, loss = 1.210426401164902
Epoch = 13, loss = 1.1010846301672061
Epoch = 14, loss = 1.0096508067390166
Epoch = 15, loss = 0.9364579402656562
Epoch = 16, loss = 0.8805476877643649
Epoch = 17, loss = 0.8396283384360232
Epoch = 18, loss = 0.8105557035491257
Epoch = 19, loss = 0.7900770060423484
Epoch = 20, loss = 0.7754258748138174
Epoch = 21, loss = 0.7645636892059197
Epoch = 22, loss = 0.7561278190767923
Epoch = 23, loss = 0.7492597619292389
Epoch = 24, loss = 0.7434352696176206
Epoch = 25, loss = 0.7383379566603642
Epoch = 26, loss = 0.7337761788695178
Epoch = 27, loss = 0.7296316895695261
Epoch = 28, loss = 0.7258290274132055
Epoch = 29, loss = 0.7223176556666342
Epoch = 30, loss = 0.7190616831827072
Epoch = 31, loss = 0.7160339967785084
Epoch = 32, loss = 0.7132129226376073
Epoch = 33, loss = 0.7105803224322423
Epoch = 34, loss = 0.7081204974521371
Epoch = 35, loss = 0.7058195458127473
Epoch = 36, loss = 0.7036649734530549
Epoch = 37, loss = 0.7016454477437019
Epoch = 38, loss = 0.6997506319563429
Epoch = 39, loss = 0.6979710663743836
Epoch = 40, loss = 0.6962980770712591
Epoch = 41, loss = 0.6947237017926657
Epoch = 42, loss = 0.6932406270091802
Epoch = 43, loss = 0.6918421327551952
Epoch = 44, loss = 0.6905220432780054
Epoch = 45, loss = 0.6892746823030981
Epoch = 46, loss = 0.6880948321604955
Epoch = 47, loss = 0.6869776962665786
Epoch = 48, loss = 0.6859188646003761
Epoch = 49, loss = 0.6849142818990264
Epoch = 50, loss = 0.683960218349449

In [85]:
model.weights

tensor([[-0.1632],
        [ 0.0707],
        [ 0.1768],
        [-0.0384],
        [-0.1631],
        [ 0.3662],
        [-0.0890],
        [-0.3199],
        [-0.1948],
        [-0.0275],
        [ 0.0042],
        [-0.1667],
        [-0.2345],
        [ 0.5368],
        [ 0.1625],
        [ 0.0926],
        [-0.1219],
        [-0.1588],
        [ 0.3613],
        [-0.2360],
        [ 0.1529],
        [ 0.1236],
        [-0.3514],
        [ 0.0902],
        [-0.1097],
        [-0.4344],
        [ 0.1739],
        [ 0.2936],
        [-0.0754],
        [ 0.5000]], dtype=torch.float64, requires_grad=True)

In [86]:
model.bias

tensor([-0.3716], dtype=torch.float64, requires_grad=True)

Evaluation

In [89]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    acc = (y_pred == y_test_tensor).float().mean()
    
print(acc)

tensor(0.5512)